# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "cleanerBotA"
  limits:
    linear: [0.7, 0.5] # velocity, acceleration
    angular: [0.4, 1.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 1.0 # radius in m
    vicinity: 1.2 # radius in m
  reversible: False # whether robots in this fleet can reverse
  # TODO Update battery parameters with actual specs
  battery_system:
    voltage: 24.0 # V
    capacity: 20.0 # Ahr
    charging_current: 10.0 # A
  mechanical_system:
    mass: 70.0 # kg
    moment_of_inertia: 40.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 100.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.20 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: False
    delivery: False
  actions: ["clean"]
  finishing_request: "park" # [park, charge, nothing]
  robots:
    cleanerBotA_1:
      charger: "cleanerbot_charger1"
    cleanerBotA_2:
      charger: "cleanerbot_charger2"

fleet_manager:
  ip: "127.0.0.1"
  port: 22013
  user: "some_user"
  password: "some_password"
  robot_state_update_frequency: 10.0
  action_paths:
    clean:
      clean_lobby:
        map_name: "L1"
        path: [ [24.59, -35.49, 0.0],
                [24.24, -38.77, 1.57],
                [18.3, -38.62, 0.0],
                [18.3, -35.3, 0.0],
                [23.8, -35.45, 0.0] ]
        finish_waypoint: "clean_lobby"
      clean_waiting_area:
        map_name: "L1"
        path: [ [8.54, -21.93, 1.57],
                [14.0, -23.25, 0.0],
                [14.0, -24.7, 0.0],
                [8.6, -24.7, 1.57],
                [8.56, -23.27, 0.0] ]
        finish_waypoint: "clean_waiting_area"
      clean_restaurant:
        map_name: "L1"
        path: [ [14.2, -11.35, 1.57],
                [16.5, -11.35, 1.57],
                [17.8, -13.9, 0.0],
                [12.8, -14.1, 0.0],
                [12.86, -11.4, 0.0] ]
        finish_waypoint: "clean_restaurant"

