# This docking config file provides the mock docker a series of known paths which
# the cleaner robot will follow during a docking (aka cleaning) process. 
#   Example:  Destination: "CLEANZONE" ;  The path here is the trajactory 
#             which starts from "CLEANZONE_start" to "CLEANZONE"

cleanerBotA:
  zone_1: 
    level_name: "L1"
    path: [ [121.3, -26.76, 0.0],
            [121.1, -17.44, 1.57],
            [116.2, -17.44, 0.0],
            [116.2, -26.60, 1.57],
            [110.6, -26.60, 3.14],
            [110.6, -17.44, 1.57],
            [105.9, -17.44, 0.0],
            [105.9, -32.1, 0.0],
            [121.5, -30.35, -1.57],
            [121.3, -28.3, 0.0] ]
  zone_2:
    level_name: "L1"
    path: [ [149.00, -29.22, 0.0],
            [129.4, -29.67, -1.57],
            [129.4, -24.76, -1.57],
            [149.0, -24.76, 3.14],
            [149.0, -27.11, 0.0] ]
  zone_3: 
    level_name: "L1"
    path: [ [154.4, -29.51, -1.57],
            [169.9, -29.79, -0.8], 
            [173.1, -26.41, 1.57],
            [173.1, -23.26, 3.14],
            [154.4, -23.26, -1.57],
            [154.4, -25.00, -1.57],
            [168.5, -25.00, 3.14],
            [168.5, -27.60, 1.57],
            [154.4, -27.60, 0.0]]
  zone_4:
    level_name: "L1"
    path: [ [152.0, -55.6, 0.0],
            [123.1, -55.6, 0.0],
            [123.1, -57.14, 0.0],
            [148.5, -57.14, 0.0],
            [148.5, -59.34, 0.0],
            [148.5, -59.34, 0.0],
            [123.0, -59.06, 0.0],
            [123.0, -60.8, 0.0],
            [152.0, -60.3, 0.0] ]
cleanerBotE:
  zone_2:
    level_name: "L1"
    path: [ [149.00, -29.22, 0.0],
            [129.4, -29.67, -1.57],
            [129.4, -24.76, -1.57],
            [149.0, -24.76, 3.14],
            [149.0, -27.11, 0.0] ]
  zone_3: 
    level_name: "L1"
    path: [ [154.4, -29.51, -1.57],
            [169.9, -29.79, -0.8], 
            [173.1, -26.41, 1.57],
            [173.1, -23.26, 3.14],
            [154.4, -23.26, -1.57],
            [154.4, -25.00, -1.57],
            [168.5, -25.00, 3.14],
            [168.5, -27.60, 1.57],
            [154.4, -27.60, 0.0]]
  zone_4:
    level_name: "L1"
    path: [ [152.0, -55.6, 0.0],
            [123.1, -55.6, 0.0],
            [123.1, -57.14, 0.0],
            [148.5, -57.14, 0.0],
            [148.5, -59.34, 0.0],
            [148.5, -59.34, 0.0],
            [123.0, -59.06, 0.0],
            [123.0, -60.8, 0.0],
            [152.0, -60.3, 0.0] ]
