# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "deliveryRobot"
  fleet_manager:
    ip: "127.0.0.1"
    port: 22012
    user: "some_user"
    password: "some_password"
  limits:
    linear: [0.7, 0.75] # velocity, acceleration
    angular: [0.6, 2.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.6 # radius in m
    vicinity: 0.8 # radius in m
  reversible: True # whether robots in this fleet can reverse
  # TODO Update battery parameters with actual specs
  battery_system:
    voltage: 24.0 # V
    capacity: 40.0 # Ahr
    charging_current: 8.8 # A
  mechanical_system:
    mass: 70.0 # kg
    moment_of_inertia: 40.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    clean: False
    finishing_request: "park" # [park, charge, nothing]

# DeliveryRobot CONFIG =================================================================

robots:
  # Here the user is expected to append the configuration for each robot in the
  # fleet.
  # Configuration for deliveryRobot_1
  deliveryRobot_1:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "L1_sub_waiting_area_1"
        orientation: 0.0 # radians
      charger:
        waypoint: "L1_sub_waiting_area_1"
  # Configuration for deliveryRobot_2
  deliveryRobot_2:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "deliveryRobot_2_charger"
        orientation: 0.0 # radians
      charger:
        waypoint: "deliveryRobot_2_charger"
