# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "tinyRobot"
  limits:
    linear: [0.5, 0.75] # velocity, acceleration
    angular: [0.6, 2.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.3 # radius in m
    vicinity: 0.5 # radius in m
  reversible: True # whether robots in this fleet can reverse
  battery_system:
    voltage: 12.0 # V
    capacity: 24.0 # Ahr
    charging_current: 5.0 # A
  mechanical_system:
    mass: 20.0 # kg
    moment_of_inertia: 10.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: True
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    clean: False
    finishing_request: "park" # [park, charge, nothing]

# DeliveryBot CONFIG =================================================================

robots:
  # Here the user is expected to append the configuration for each robot in the
  # fleet.
  # Configuration for first robot in this fleet
  tinyRobot1:
    robot_config:
      base_url: "http://127.0.0.1:8001" # API endpoint for the robot
      user: "some_user"
      password: "some_password"
      max_delay: 10.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
      filter_waypoints: True
    rmf_config:
      robot_state_update_frequency: 1.0
      start:
        map_name: "L1"
        waypoint: "tinyRobot1_charger"
        orientation: 0.0 # radians
      charger:
        waypoint: "tinyRobot1_charger"
  # Configuration for the second robot in this fleet if there is a second robot
  tinyRobot2:
    robot_config:
      base_url: "http://127.0.0.1:8001" # API endpoint for the robot
      user: "some_user"
      password: "some_password"
      max_delay: 10.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
      filter_waypoints: True
    rmf_config:
      robot_state_update_frequency: 1.0
      start:
        map_name: "L1"
        waypoint: "tinyRobot2_charger"
        orientation: 0.0 # radians
      charger:
        waypoint: "tinyRobot2_charger"

# TRANSFORM CONFIG =============================================================
# For computing transforms between Robot and RMF coordinate systems

reference_coordinates:
  rmf: [[20.42, -5.312],
        [10.43, -5.575],
        [16.85, -5.404],
        [20.95, -7.497]]
  robot: [[20.42, -5.312],
        [10.43, -5.575],
        [16.85, -5.404],
        [20.95, -7.497]]
