# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "deliveryRobot"
  limits:
    linear: [0.5, 0.75] # velocity, acceleration
    angular: [0.6, 2.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.3 # radius in m
    vicinity: 0.5 # radius in m
  reversible: False # whether robots in this fleet can reverse
  battery_system:
    voltage: 12.0 # V
    capacity: 24.0 # Ahr
    charging_current: 5.0 # A
  mechanical_system:
    mass: 20.0 # kg
    moment_of_inertia: 10.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: False
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: False
    clean: False
    finishing_request: "charge" # [park, charge, nothing]

# DeliveryBot CONFIG =================================================================

robots:
  # Here the user is expected to append the configuration for each robot in the
  # fleet.
  # Configuration for first robot in this fleet
  deliveryRobot_1:
    robot_config:
      offset_x: 22000
      offset_y: 31500
      base_url: "http://0.0.0.0:8080" # API endpoint for the robot
      user: "some_user"
      password: "some_password"
      fleet_name: "DeliveryRobot"
      max_delay: 10000.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 0.5
      start:
        map_name: "L1"
        # waypoint: "charger_deliverybot1" # Optional
        # orientation: 0.0 # Optional, radians
        waypoint: null
        orientation: null
      charger:
        waypoint: "room_5"
  deliveryRobot_2:
    robot_config:
      offset_x: 22000
      offset_y: 31500
      base_url: "http://0.0.0.0:8080" # API endpoint for the robot
      user: "some_user"
      password: "some_password"
      fleet_name: "DeliveryRobot"
      max_delay: 10000.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 0.5
      start:
        map_name: "L1"
        # waypoint: "charger_deliverybot1" # Optional
        # orientation: 0.0 # Optional, radians
        waypoint: null
        orientation: null
      charger:
        waypoint: "room_6"
  deliveryRobot_3:
    robot_config:
      offset_x: 22000
      offset_y: 31500
      base_url: "http://0.0.0.0:8080" # API endpoint for the robot
      user: "some_user"
      password: "some_password"
      fleet_name: "DeliveryRobot"
      max_delay: 10000.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 0.5
      start:
        map_name: "L1"
        # waypoint: "charger_deliverybot1" # Optional
        # orientation: 0.0 # Optional, radians
        waypoint: null
        orientation: null
      charger:
        waypoint: "room_2"

reference_coordinates:
  rmf: [[20.33, -3.156],
        [8.908, -2.57],
        [13.02, -3.601],
        [21.93, -4.124]]
  robot: [[20.33, -3.156],
          [8.908, -2.57],
          [13.02, -3.601],
          [21.93, -4.124]]
