name: style
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image: ['ros:rolling-ros-base']
    container:
      image: ${{ matrix.docker_image }}
    steps:
    - uses: actions/checkout@v3
    - name: deps
      shell: bash
      run: |
        sudo apt update && sudo apt install pycodestyle
    - name: pycodestyle
      shell: bash
      run: |
        pycodestyle .
